### ISSUE TITLE
Sequencer: mousewheel over H and V zoom alters slider but don't affect zoom

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#16]
As title.

**Comment by j3ffhubb** [comment]
I have a fix coming right now;  It's going to be disabling that event (and some others) to prevent the cosmetic bug.  MusiKernel doesn't use Qt's built in scaling facilities because they look terrible, so it recalculates everything and draws things at the size they need to be.  That looks much better, but there is the side effect of drawing very slow when rescaling a large project, which is why those sliders don't directly scale the project, but provide a visual indicator and then only scale on release (which is why mouse wheel events don't make sense, they would be too slow and jerky if they were allowed to scale the sequencer).
