### ISSUE TITLE
Piano Roll: if a synth note block is too short, sustain setting isn't respected

### ISSUE THREAD

**Issue by milkmiruku** [j3ffhubb/musikernel#17]
I was working in 8th notes then switched to 16ths to add an ornament, however, on playback, the 16th notes took a few seconds to end, rather than the expected quarter second or so, i.e., the envelope doesn't 'fit' in the block, whereas one might expect a block to represent a note press(?).

There is a related issue in that pressing stop _right_ after a note starts gives the same problem.

**Comment by j3ffhubb** [comment]
Does the synthesizer patch you're using have a short attack, a short-to-medium decay, a low sustain and a long release on it's master ADSR envelope?  It sounds to me like the note is too short for the decay phase to finish, so it's releasing from a much higher amplitude than the sustain.

It's a tricky problem that has plagued synthesizer designers for decades;  If you commit to finishing the decay phase regardless of when the note was released, then you're not really respecting the note length, quickly jumping to the sustain amplitude would sound very un-natural, so that leaves this situation.

I'd try tweaking the ADSR envelope;  namely: shorter release (possibly add a Simple Reverb plugin to add more tail if needed), and possibly shorter decay.  You can actually tempo sync decay time by right-clicking on the knob and selecting the "Tempo Sync..." dialog, then syncing to 1/16th note (if attack is not zero, then you may need to dial it down more).

If I'm not understanding correctly, then please provide more info.  Zipping up the project folder and sending it to me is most helpful, but if you would prefer not to do that, then screenshots of the MIDI item and synth in question is the next best thing.

**Comment by milkmiruku** [comment]
Yes, that describes the patch, and thank you for the detailed response, that explains the situation and a solution! A tricky problem and a lack of user awareness.
